[project]
name = "harco-md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "icecream>=2.1.5",
    "openai>=1.95.1",
    "pygame>=2.6.1",
    "python-dotenv>=1.1.1",
    "rich>=14.0.0",
]
